services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgres

      - key: DB_POSTGRESDB_DATABASE
        value: postgres 

      - key: DB_POSTGRESDB_HOST
        value: iibkjzmvuftcwlycxyqh.supabase.co  

      - key: DB_POSTGRESDB_PASSWORD
        value: ${DB_PASSWORD} 

      - key: DB_POSTGRESDB_USER
        value: postgres

      - key: WEBHOOK_URL
        value: https://n8n-xxxx.onrender.com 

      - key: N8N_BASIC_AUTH_ACTIVE
        value: true

      - key: N8N_BASIC_AUTH_USER
        value: admin

      - key: N8N_BASIC_AUTH_PASSWORD
        value: ${ADMIN_PASSWORD} 
